/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DialogEnterpriseAddressDetails.java
 *
 * Created on May 15, 2012, 5:00:35 PM
 */
package vn.com.hkt.em.enterprise.presentation.panel.spi.dialog;

/**
 *
 * @author duong
 */
public class DialogEnterpriseAddressDetails extends javax.swing.JDialog {

    /** Creates new form DialogEnterpriseAddressDetails */
    public DialogEnterpriseAddressDetails(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public DialogEnterpriseAddressDetails(){
           initComponents();
        this.setModal(true);
        this.setLocationRelativeTo(null);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDownFooter = new javax.swing.JButton();
        btnDown = new javax.swing.JButton();
        btnUp = new javax.swing.JButton();
        btnUpHeader = new javax.swing.JButton();
        lbMessenger = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        btnRemove = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        txtFax = new javax.swing.JTextField();
        txtTelephone = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        cbCity = new javax.swing.JComboBox();
        cbCountry = new javax.swing.JComboBox();
        txtEnterpriseName = new javax.swing.JTextField();
        lbFax = new javax.swing.JLabel();
        lbTelephone = new javax.swing.JLabel();
        lbAddress = new javax.swing.JLabel();
        lbCity = new javax.swing.JLabel();
        lbCountry = new javax.swing.JLabel();
        lbEnterpriseName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnDownFooter.setText(org.openide.util.NbBundle.getMessage(DialogEnterpriseAddressDetails.class, "DialogEnterpriseAddressDetails.btnDownFooter.text")); // NOI18N

        btnDown.setText(org.openide.util.NbBundle.getMessage(DialogEnterpriseAddressDetails.class, "DialogEnterpriseAddressDetails.btnDown.text")); // NOI18N

        btnUp.setText(org.openide.util.NbBundle.getMessage(DialogEnterpriseAddressDetails.class, "DialogEnterpriseAddressDetails.btnUp.text")); // NOI18N

        btnUpHeader.setText(org.openide.util.NbBundle.getMessage(DialogEnterpriseAddressDetails.class, "DialogEnterpriseAddressDetails.btnUpHeader.text")); // NOI18N

        lbMessenger.setForeground(new java.awt.Color(255, 0, 0));
        lbMessenger.setText(org.openide.util.NbBundle.getMessage(DialogEnterpriseAddressDetails.class, "DialogEnterpriseAddressDetails.lbMessenger.text")); // NOI18N

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(table);

        btnRemove.setText(org.openide.util.NbBundle.getMessage(DialogEnterpriseAddressDetails.class, "DialogEnterpriseAddressDetails.btnRemove.text")); // NOI18N

        btnRefresh.setText(org.openide.util.NbBundle.getMessage(DialogEnterpriseAddressDetails.class, "DialogEnterpriseAddressDetails.btnRefresh.text")); // NOI18N

        btnEdit.setText(org.openide.util.NbBundle.getMessage(DialogEnterpriseAddressDetails.class, "DialogEnterpriseAddressDetails.btnEdit.text")); // NOI18N

        btnReset.setText(org.openide.util.NbBundle.getMessage(DialogEnterpriseAddressDetails.class, "DialogEnterpriseAddressDetails.btnReset.text")); // NOI18N

        btnAdd.setText(org.openide.util.NbBundle.getMessage(DialogEnterpriseAddressDetails.class, "DialogEnterpriseAddressDetails.btnAdd.text")); // NOI18N

        txtFax.setText(org.openide.util.NbBundle.getMessage(DialogEnterpriseAddressDetails.class, "DialogEnterpriseAddressDetails.txtFax.text")); // NOI18N

        txtTelephone.setText(org.openide.util.NbBundle.getMessage(DialogEnterpriseAddressDetails.class, "DialogEnterpriseAddressDetails.txtTelephone.text")); // NOI18N

        txtAddress.setColumns(20);
        jScrollPane1.setViewportView(txtAddress);

        cbCity.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbCountry.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtEnterpriseName.setEditable(false);
        txtEnterpriseName.setText(org.openide.util.NbBundle.getMessage(DialogEnterpriseAddressDetails.class, "DialogEnterpriseAddressDetails.txtEnterpriseName.text")); // NOI18N

        lbFax.setText(org.openide.util.NbBundle.getMessage(DialogEnterpriseAddressDetails.class, "DialogEnterpriseAddressDetails.lbFax.text")); // NOI18N

        lbTelephone.setText(org.openide.util.NbBundle.getMessage(DialogEnterpriseAddressDetails.class, "DialogEnterpriseAddressDetails.lbTelephone.text")); // NOI18N

        lbAddress.setText(org.openide.util.NbBundle.getMessage(DialogEnterpriseAddressDetails.class, "DialogEnterpriseAddressDetails.lbAddress.text")); // NOI18N

        lbCity.setText(org.openide.util.NbBundle.getMessage(DialogEnterpriseAddressDetails.class, "DialogEnterpriseAddressDetails.lbCity.text")); // NOI18N

        lbCountry.setText(org.openide.util.NbBundle.getMessage(DialogEnterpriseAddressDetails.class, "DialogEnterpriseAddressDetails.lbCountry.text")); // NOI18N

        lbEnterpriseName.setText(org.openide.util.NbBundle.getMessage(DialogEnterpriseAddressDetails.class, "DialogEnterpriseAddressDetails.lbEnterpriseName.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbMessenger, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUpHeader)
                            .addComponent(btnUp)
                            .addComponent(btnDown)
                            .addComponent(btnDownFooter))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbEnterpriseName)
                            .addComponent(lbCountry)
                            .addComponent(lbCity)
                            .addComponent(lbAddress)
                            .addComponent(lbTelephone))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTelephone, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
                            .addComponent(cbCity, 0, 475, Short.MAX_VALUE)
                            .addComponent(cbCountry, 0, 475, Short.MAX_VALUE)
                            .addComponent(txtEnterpriseName, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbFax)
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnReset)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAdd)
                                .addGap(6, 6, 6)
                                .addComponent(btnRefresh)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEdit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRemove))
                            .addComponent(txtFax, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEnterpriseName)
                    .addComponent(txtEnterpriseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCountry)
                    .addComponent(cbCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCity)
                    .addComponent(cbCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbAddress)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTelephone)
                    .addComponent(txtTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbFax)
                    .addComponent(txtFax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAdd)
                        .addComponent(btnReset))
                    .addComponent(btnRefresh)
                    .addComponent(btnEdit)
                    .addComponent(btnRemove))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbMessenger)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnUpHeader)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDown)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDownFooter)
                        .addGap(251, 251, 251))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogEnterpriseAddressDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogEnterpriseAddressDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogEnterpriseAddressDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogEnterpriseAddressDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                DialogEnterpriseAddressDetails dialog = new DialogEnterpriseAddressDetails(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDown;
    private javax.swing.JButton btnDownFooter;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnUp;
    private javax.swing.JButton btnUpHeader;
    private javax.swing.JComboBox cbCity;
    private javax.swing.JComboBox cbCountry;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbAddress;
    private javax.swing.JLabel lbCity;
    private javax.swing.JLabel lbCountry;
    private javax.swing.JLabel lbEnterpriseName;
    private javax.swing.JLabel lbFax;
    private javax.swing.JLabel lbMessenger;
    private javax.swing.JLabel lbTelephone;
    private javax.swing.JTable table;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtEnterpriseName;
    private javax.swing.JTextField txtFax;
    private javax.swing.JTextField txtTelephone;
    // End of variables declaration//GEN-END:variables
}
