/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DialogEnterpriseBusinessAreaDetails.java
 *
 * Created on May 14, 2012, 4:10:21 PM
 */
package vn.com.hkt.em.enterprise.presentation.panel.spi.dialog;

import java.util.ArrayList;
import java.util.List;
import vn.com.hkt.em.basic.data.entities.Enterprise;
import vn.com.hkt.em.common.event.KeyControlPress;
import vn.com.hkt.em.enterprise.data.access.api.IBusinessAreaDAO;
import vn.com.hkt.em.enterprise.data.access.spi.BusinessAreaDAO;
import vn.com.hkt.em.enterprise.data.entities.EnterpriseBusinessArea;
import vn.com.hkt.em.enterprise.presentation.dialog.spi.DialogBusinessArea;
import vn.com.hkt.em.enterprise.presentation.panel.api.IPanelShowEnterpriseBusinessArea;
import vn.com.hkt.em.enterprise.presentation.panel.spi.PanelShowEnterpriseBusinessAreaDetails;
import vn.com.hkt.em.enterprise.presentation.panel.spi.table.model.TableModelEnterpriseBusinessArea;

/**
 *
 * @author duong
 */
public class DialogEnterpriseBusinessAreaDetails extends javax.swing.JDialog {

    private List<EnterpriseBusinessArea> businessAreaOfEnterprise;
    private IBusinessAreaDAO businessAreaDAO = new BusinessAreaDAO();
    private IPanelShowEnterpriseBusinessArea panelShowEnterpriseBusinessAreaDetails = new PanelShowEnterpriseBusinessAreaDetails();    
    private Enterprise enterprise;
    private KeyControlPress keyControlPress = new KeyControlPress();// thực hiện bàn phím mở form

    /** Creates new form DialogEnterpriseBusinessAreaDetails */
    public DialogEnterpriseBusinessAreaDetails(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public DialogEnterpriseBusinessAreaDetails() {
        initComponents();
        this.setModal(true);
        this.setLocationRelativeTo(null);        
       
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbEnterprise = new javax.swing.JLabel();
        lbMessenger = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        btnUpHeader = new javax.swing.JButton();
        btnUp = new javax.swing.JButton();
        btnDown = new javax.swing.JButton();
        btnDownFooter = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        lbDescription = new javax.swing.JLabel();
        txtRanking = new javax.swing.JTextField();
        lbRanking = new javax.swing.JLabel();
        cbBusinessArea = new javax.swing.JComboBox();
        lbBusinessArea = new javax.swing.JLabel();
        txtEnterpriseName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbEnterprise.setText(org.openide.util.NbBundle.getMessage(DialogEnterpriseBusinessAreaDetails.class, "DialogEnterpriseBusinessAreaDetails.lbEnterprise.text")); // NOI18N

        lbMessenger.setForeground(new java.awt.Color(255, 0, 0));
        lbMessenger.setText(org.openide.util.NbBundle.getMessage(DialogEnterpriseBusinessAreaDetails.class, "DialogEnterpriseBusinessAreaDetails.lbMessenger.text")); // NOI18N

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        btnUpHeader.setText(org.openide.util.NbBundle.getMessage(DialogEnterpriseBusinessAreaDetails.class, "DialogEnterpriseBusinessAreaDetails.btnUpHeader.text")); // NOI18N

        btnUp.setText(org.openide.util.NbBundle.getMessage(DialogEnterpriseBusinessAreaDetails.class, "DialogEnterpriseBusinessAreaDetails.btnUp.text")); // NOI18N

        btnDown.setText(org.openide.util.NbBundle.getMessage(DialogEnterpriseBusinessAreaDetails.class, "DialogEnterpriseBusinessAreaDetails.btnDown.text")); // NOI18N

        btnDownFooter.setText(org.openide.util.NbBundle.getMessage(DialogEnterpriseBusinessAreaDetails.class, "DialogEnterpriseBusinessAreaDetails.btnDownFooter.text")); // NOI18N

        btnEdit.setText(org.openide.util.NbBundle.getMessage(DialogEnterpriseBusinessAreaDetails.class, "DialogEnterpriseBusinessAreaDetails.btnEdit.text")); // NOI18N

        btnAdd.setText(org.openide.util.NbBundle.getMessage(DialogEnterpriseBusinessAreaDetails.class, "DialogEnterpriseBusinessAreaDetails.btnAdd.text")); // NOI18N

        btnReset.setText(org.openide.util.NbBundle.getMessage(DialogEnterpriseBusinessAreaDetails.class, "DialogEnterpriseBusinessAreaDetails.btnReset.text")); // NOI18N

        btnRefresh.setText(org.openide.util.NbBundle.getMessage(DialogEnterpriseBusinessAreaDetails.class, "DialogEnterpriseBusinessAreaDetails.btnRefresh.text")); // NOI18N

        btnRemove.setText(org.openide.util.NbBundle.getMessage(DialogEnterpriseBusinessAreaDetails.class, "DialogEnterpriseBusinessAreaDetails.btnRemove.text")); // NOI18N

        txtDescription.setColumns(20);
        jScrollPane2.setViewportView(txtDescription);

        lbDescription.setText(org.openide.util.NbBundle.getMessage(DialogEnterpriseBusinessAreaDetails.class, "DialogEnterpriseBusinessAreaDetails.lbDescription.text")); // NOI18N

        txtRanking.setText(org.openide.util.NbBundle.getMessage(DialogEnterpriseBusinessAreaDetails.class, "DialogEnterpriseBusinessAreaDetails.txtRanking.text")); // NOI18N

        lbRanking.setText(org.openide.util.NbBundle.getMessage(DialogEnterpriseBusinessAreaDetails.class, "DialogEnterpriseBusinessAreaDetails.lbRanking.text")); // NOI18N

        cbBusinessArea.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbBusinessArea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbBusinessAreaMouseClicked(evt);
            }
        });

        lbBusinessArea.setText(org.openide.util.NbBundle.getMessage(DialogEnterpriseBusinessAreaDetails.class, "DialogEnterpriseBusinessAreaDetails.lbBusinessArea.text")); // NOI18N

        txtEnterpriseName.setEditable(false);
        txtEnterpriseName.setText(org.openide.util.NbBundle.getMessage(DialogEnterpriseBusinessAreaDetails.class, "DialogEnterpriseBusinessAreaDetails.txtEnterpriseName.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbRanking))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbDescription))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUpHeader)
                            .addComponent(btnUp)
                            .addComponent(btnDown)
                            .addComponent(btnDownFooter))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbMessenger, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lbBusinessArea))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lbEnterprise)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEnterpriseName, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnReset)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAdd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRefresh)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEdit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRemove))
                            .addComponent(cbBusinessArea, 0, 510, Short.MAX_VALUE)
                            .addComponent(txtRanking, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEnterprise)
                    .addComponent(txtEnterpriseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbBusinessArea)
                    .addComponent(cbBusinessArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbRanking)
                    .addComponent(txtRanking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDescription)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReset)
                    .addComponent(btnAdd)
                    .addComponent(btnRefresh)
                    .addComponent(btnEdit)
                    .addComponent(btnRemove))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbMessenger)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnUpHeader)
                        .addGap(18, 18, 18)
                        .addComponent(btnUp)
                        .addGap(18, 18, 18)
                        .addComponent(btnDown)
                        .addGap(18, 18, 18)
                        .addComponent(btnDownFooter))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
// an phim + kick chuot mo form 
private void cbBusinessAreaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbBusinessAreaMouseClicked
   if(keyControlPress.isKeyCTRL()){
       DialogBusinessArea dialogBusinessArea = new DialogBusinessArea();
       dialogBusinessArea.setComboBox(cbBusinessArea);
       dialogBusinessArea.setVisible(true);
       keyControlPress.setKeyCTRL(false);            
   }   
    cbBusinessArea.addKeyListener(keyControlPress);
}//GEN-LAST:event_cbBusinessAreaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogEnterpriseBusinessAreaDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogEnterpriseBusinessAreaDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogEnterpriseBusinessAreaDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogEnterpriseBusinessAreaDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                DialogEnterpriseBusinessAreaDetails dialog = new DialogEnterpriseBusinessAreaDetails(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDown;
    private javax.swing.JButton btnDownFooter;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnUp;
    private javax.swing.JButton btnUpHeader;
    private javax.swing.JComboBox cbBusinessArea;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbBusinessArea;
    private javax.swing.JLabel lbDescription;
    private javax.swing.JLabel lbEnterprise;
    private javax.swing.JLabel lbMessenger;
    private javax.swing.JLabel lbRanking;
    private javax.swing.JTable table;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextField txtEnterpriseName;
    private javax.swing.JTextField txtRanking;
    // End of variables declaration//GEN-END:variables

    public void setIPanelShowEnterpriseBusinessArea(IPanelShowEnterpriseBusinessArea panelShowEnterpriseBusinessAreaDetails) {
        this.panelShowEnterpriseBusinessAreaDetails = panelShowEnterpriseBusinessAreaDetails;
    }

    public void setBusinessAreaOfEnterprise(Enterprise enterprise, List<EnterpriseBusinessArea> businessAreas) {
        this.enterprise = enterprise;
        this.businessAreaOfEnterprise = businessAreas;
        if (enterprise != null) {
            txtEnterpriseName.setText(enterprise.getEnterpriseName());
        } else {
            this.enterprise = new Enterprise();
            txtEnterpriseName.setText("");
        }
        if (businessAreas == null) {
            businessAreas = new ArrayList<EnterpriseBusinessArea>();
        }
        loadListIdBusinessAreaOfEnterprise();
        loadTable();

    }

    private void loadListIdBusinessAreaOfEnterprise() {
    }

    private void loadTable() {
        TableModelEnterpriseBusinessArea model = new TableModelEnterpriseBusinessArea(businessAreaOfEnterprise);
        table.setModel(model);
    }
}
