/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelShowEnterpriseBusinessAreaOverview.java
 *
 * Created on May 14, 2012, 3:57:08 PM
 */
package vn.com.hkt.em.enterprise.presentation.panel.overview.spi;

import javax.swing.JPanel;
import org.openide.util.lookup.ServiceProvider;
import vn.com.hkt.em.basic.data.entities.Enterprise;
import vn.com.hkt.em.basic.presentation.panel.show.api.IPanelShowEnterpriseBaisc;
import vn.com.hkt.em.enterprise.presentation.panel.api.IPanelShowEnterpriseBusinessArea;
import vn.com.hkt.em.enterprise.presentation.panel.spi.PanelShowEnterpriseBusinessAreaDetails;
import vn.com.hkt.em.enterprise.presentation.panel.spi.dialog.DialogEnterpriseBusinessAreaDetails;

/**
 *
 * @author duong
 */
@ServiceProvider(service = IPanelShowEnterpriseBaisc.class)
public class PanelShowEnterpriseBusinessAreaOverview extends javax.swing.JPanel implements IPanelShowEnterpriseBaisc {

    /** Creates new form PanelShowEnterpriseBusinessAreaOverview */ 
    private final long LEVEL_ENTERPRISE_BAISC = 3;
    private IPanelShowEnterpriseBusinessArea panelShowEnterpriseBusinessAreaDetails;

    public PanelShowEnterpriseBusinessAreaOverview() {
        initComponents();
            loadExtention();
            panelShowEnterpriseBusinessAreaDetails= new PanelShowEnterpriseBusinessAreaDetails();
            jScrollPane1.setViewportView((JPanel)panelShowEnterpriseBusinessAreaDetails);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        btnInformationOpen = new javax.swing.JButton();
        btnInformationEdit = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), org.openide.util.NbBundle.getMessage(PanelShowEnterpriseBusinessAreaOverview.class, "PanelShowEnterpriseBusinessAreaOverview.jPanel1.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jScrollPane1.setBorder(null);

        btnInformationOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vn/com/hkt/em/enterprise/presentation/icon/open1.png"))); // NOI18N
        btnInformationOpen.setText(org.openide.util.NbBundle.getMessage(PanelShowEnterpriseBusinessAreaOverview.class, "PanelShowEnterpriseBusinessAreaOverview.btnInformationOpen.text")); // NOI18N
        btnInformationOpen.setToolTipText(org.openide.util.NbBundle.getMessage(PanelShowEnterpriseBusinessAreaOverview.class, "PanelShowEnterpriseBusinessAreaOverview.btnInformationOpen.toolTipText")); // NOI18N

        btnInformationEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vn/com/hkt/em/enterprise/presentation/icon/edit1.png"))); // NOI18N
        btnInformationEdit.setText(org.openide.util.NbBundle.getMessage(PanelShowEnterpriseBusinessAreaOverview.class, "PanelShowEnterpriseBusinessAreaOverview.btnInformationEdit.text")); // NOI18N
        btnInformationEdit.setToolTipText(org.openide.util.NbBundle.getMessage(PanelShowEnterpriseBusinessAreaOverview.class, "PanelShowEnterpriseBusinessAreaOverview.btnInformationEdit.toolTipText")); // NOI18N
        btnInformationEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInformationEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnInformationEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInformationOpen, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnInformationOpen, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnInformationEdit)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnInformationEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInformationEditActionPerformed
          DialogEnterpriseBusinessAreaDetails dialog = new DialogEnterpriseBusinessAreaDetails();
//        dialog.setIPanelShowEnterpriseBusinessArea(panelShowEnterpriseBusinessAreaDetails);
//        dialog.setBusinessAreaOfEnterprise(panelShowEnterpriseBusinessAreaDetails.getEnterprise(), panelShowEnterpriseBusinessAreaDetails.getEnterpriseBusinessAreas());
        dialog.setVisible(true);
    }//GEN-LAST:event_btnInformationEditActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInformationEdit;
    private javax.swing.JButton btnInformationOpen;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    @Override
    public long getLevelPanelShowEnterpriseBasic() {
      return LEVEL_ENTERPRISE_BAISC;
    }

    @Override
    public void setEnterprise(Enterprise enterprise) {

    }

    @Override
    public String getDescriptionPanel() {
      return "Lĩnh vực kinh doanh"; 
    }

    @Override
    public void resetData() {
      
    }

    @Override
    public long addData(long idParent) {
      return idParent;
    }

    @Override
    public void refreshData() {
        
    }

    @Override
    public void canEditData() {
    }

    @Override
    public long editData() {
       return panelShowEnterpriseBusinessAreaDetails.editData();
    }

    @Override
    public long removeData() {
        return removeData();
    }

    @Override
    public int getFunction() {
        return panelShowEnterpriseBusinessAreaDetails.getFunction();
    }

    @Override
    public boolean checkData() {
      return true;
    }

    @Override
    public void loadDefault() {
     
    }

    private void loadExtention() {
        btnInformationOpen.setEnabled(false);
    }
}
