/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelShowEnterpriseAddressOverview.java
 *
 * Created on May 16, 2012, 10:42:35 AM
 */
package vn.com.hkt.em.enterprise.presentation.panel.overview.spi;

import java.util.ArrayList;
import javax.swing.JPanel;
import org.openide.util.lookup.ServiceProvider;
import vn.com.hkt.em.basic.data.entities.Enterprise;
import vn.com.hkt.em.basic.presentation.panel.show.api.IPanelShowEnterpriseBaisc;
import vn.com.hkt.em.enterprise.data.entities.EnterpriseAddress;
import vn.com.hkt.em.enterprise.presentation.panel.api.IPanelShowEnterpriseAddress;
import vn.com.hkt.em.enterprise.presentation.panel.spi.PanelShowEnterpriseAddressDetails;
import vn.com.hkt.em.enterprise.presentation.panel.spi.dialog.DialogEnterpriseAddressDetails;

/**
 *
 * @author duong
 */
@ServiceProvider(service = IPanelShowEnterpriseBaisc.class)
public class PanelShowEnterpriseAddressOverview extends javax.swing.JPanel implements IPanelShowEnterpriseBaisc{

     private final long LEVEL_ENTERPRISE_BAISC = 4;
     private IPanelShowEnterpriseAddress panelDetails;
    /** Creates new form PanelShowEnterpriseAddressOverview */
    public PanelShowEnterpriseAddressOverview() {
        initComponents();
          panelDetails = new PanelShowEnterpriseAddressDetails();
         panelDetails.setEnterpriseAddresses(new ArrayList<EnterpriseAddress>());
        jScrollPane1.setViewportView((JPanel) panelDetails);
        loadExtention();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        btnInformationOpen = new javax.swing.JButton();
        btnInformationEdit = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), org.openide.util.NbBundle.getMessage(PanelShowEnterpriseAddressOverview.class, "PanelShowEnterpriseAddressOverview.jPanel1.border.title_2"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), java.awt.Color.black)); // NOI18N

        jScrollPane1.setBorder(null);

        btnInformationOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vn/com/hkt/em/enterprise/presentation/icon/open1.png"))); // NOI18N
        btnInformationOpen.setText(org.openide.util.NbBundle.getMessage(PanelShowEnterpriseAddressOverview.class, "PanelShowEnterpriseAddressOverview.btnInformationOpen.text_2")); // NOI18N
        btnInformationOpen.setToolTipText(org.openide.util.NbBundle.getMessage(PanelShowEnterpriseAddressOverview.class, "PanelShowEnterpriseAddressOverview.btnInformationOpen.toolTipText_2")); // NOI18N

        btnInformationEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vn/com/hkt/em/enterprise/presentation/icon/edit1.png"))); // NOI18N
        btnInformationEdit.setText(org.openide.util.NbBundle.getMessage(PanelShowEnterpriseAddressOverview.class, "PanelShowEnterpriseAddressOverview.btnInformationEdit.text_2")); // NOI18N
        btnInformationEdit.setToolTipText(org.openide.util.NbBundle.getMessage(PanelShowEnterpriseAddressOverview.class, "PanelShowEnterpriseAddressOverview.btnInformationEdit.toolTipText_2")); // NOI18N
        btnInformationEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInformationEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnInformationOpen, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInformationEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnInformationOpen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnInformationEdit)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void btnInformationEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInformationEditActionPerformed
 DialogEnterpriseAddressDetails dialogEnterpriseAddressDetails = new DialogEnterpriseAddressDetails();
 dialogEnterpriseAddressDetails.setVisible(true);
}//GEN-LAST:event_btnInformationEditActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInformationEdit;
    private javax.swing.JButton btnInformationOpen;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    @Override
    public long getLevelPanelShowEnterpriseBasic() {
       return LEVEL_ENTERPRISE_BAISC;
    }

    @Override
    public void setEnterprise(Enterprise enterprise) {
       
    }

    @Override
    public String getDescriptionPanel() {
        return "Địa chỉ doanh nghiệp";
    }

    @Override
    public void resetData() {
        
    }

    @Override
    public long addData(long idParent) {
      return idParent;
    }

    @Override
    public void refreshData() {
      
    }

    @Override
    public void canEditData() {
     
    }

    @Override
    public long editData() {
       return panelDetails.editData();
    }

    @Override
    public long removeData() {
      return 0;
    }

    @Override
    public int getFunction() {
       return panelDetails.getFunction();
    }

    @Override
    public boolean checkData() {
        return true;
    }

    @Override
    public void loadDefault() {
       
    }

    private void loadExtention() {
        btnInformationOpen.setEnabled(false);
    }
}
