/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DialogInformation.java
 *
 * Created on Apr 6, 2012, 3:21:33 PM
 */
package vn.com.hkt.em.common.gui.dialog.spi;

import javax.swing.JPanel;
import vn.com.hkt.em.common.gui.panel.controlshow.spi.PanelControlShowInformation;
import vn.com.hkt.em.common.gui.panel.show.api.IPanelShowInformation;
import vn.com.hkt.em.common.gui.panel.show.api.IPanelShowInformationOverview;

/**
 * Giao diện hiển thị dạng dialog 
 * Dành cho các trường hợp có giao diện mở rộng để hiển thị
 * Chú ý:
 * Còn thiếu hiển thị danh sách, sự kiện tắt dialog...v.v.
 * @author BinLe
 */
public class DialogInformation extends javax.swing.JDialog {

    private IPanelShowInformationOverview panelShowInformationOverview;
 private IPanelShowInformation panelShowInformation;
    /**
     * Tạo dialog hiển thị thông tin mở rộng
     * @param panelShowInformationOverview : IPanelShowInformationOverview
     * mặt nạ giao diện thông tin gọi dialog chứa giao diện thông tin
     */
    public DialogInformation(IPanelShowInformationOverview panelShowInformationOverview) {
        initComponents();
        setModal(true);
        this.setLocationRelativeTo(null);
//        this.panelShowInformationOverview = panelShowInformationOverview;
        this.panelShowInformation = panelShowInformation;  
        jScrollPane1.setViewportView((JPanel)panelShowInformation);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jScrollPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setForeground(new java.awt.Color(51, 255, 204));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Đóng dialog và trả lại giao diện cha trên dialog cho giao diện gọi dialog    
     */
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
//        panelShowInformationOverview.reloadPanelShowInformation();
         if(panelShowInformation instanceof IPanelShowInformationOverview)
            ((IPanelShowInformationOverview)panelShowInformation).reloadPanelShowInformation();
    }//GEN-LAST:event_formWindowClosing
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    /**
     * Truyền vào giao diện điều khiển hiển thị thông tin và hiển thị giao diện đó
     * @param panelControlShowInformation :PanelControlShowInformation/
     * giao diện điều khiển hiển thị thông tin
     */
    public void setPanelControlshowInformation(PanelControlShowInformation panelControlShowInformation) {
        if (panelControlShowInformation instanceof JPanel) {
            JPanel panel= (JPanel) panelControlShowInformation;                        
            this.pack();
            jScrollPane1.setViewportView(panel);
            setVisible(true);
        }
    }
}
