/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelShowListEnterprise.java
 *
 * Created on May 2, 2012, 4:05:45 PM
 */
package vn.com.hkt.em.basic.presentation.panel.show.spi;

import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import org.openide.util.Lookup;
import org.openide.util.lookup.ServiceProvider;
import vn.com.hkt.em.basic.business.provide.panel.api.IProviderPanelShowListEnterprise;
import vn.com.hkt.em.basic.business.providei.panel.spi.ProviderPanelShowListEnterprise;
import vn.com.hkt.em.basic.data.entities.Enterprise;
import vn.com.hkt.em.basic.presentation.manager.ManagerPresentationEnterprise;
import vn.com.hkt.em.basic.presentation.panel.show.api.IPanelShowEnterpriseBaisc;
import vn.com.hkt.em.basic.presentation.panel.show.api.IPanelShowListEnterpriseBasic;
import vn.com.hkt.em.basic.presentation.panel.show.spi.tablemodel.ListEnterpriseTableModel;
import vn.com.hkt.em.common.gui.controlshow.api.IControlShowListInformation;
import vn.com.hkt.em.common.gui.dialog.spi.DialogInformation;

/**
 *
 * @author BinLe
 */
@ServiceProvider(service = IPanelShowListEnterpriseBasic.class)
public class PanelShowListEnterprise extends javax.swing.JPanel implements IPanelShowListEnterpriseBasic {

    private final long LEVEL = 1;
    private IControlShowListInformation controlShowListInformation;
    private Enterprise BE_EnterpriseChoise;
    private IProviderPanelShowListEnterprise provider = new ProviderPanelShowListEnterprise();//DAO
    private List<IPanelShowEnterpriseBaisc> panelShowEnterpriseBaiscs =
            (List<IPanelShowEnterpriseBaisc>) Lookup.getDefault().lookupAll(IPanelShowEnterpriseBaisc.class);
      private boolean firstClick = false;
//    private PopUpCommon popUpCommon;
//    private boolean hadLoadPopUp = false;
//    private PanelPopUp panelPopUp;
  

    /** Creates new form PanelShowListEnterprise */
    public PanelShowListEnterprise() {
        initComponents();
        loadDataDefault();

        cbSearch.setModel(new DefaultComboBoxModel(provider.getListTypeSearch()));//load dl cua cb len 

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbSearch = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableListEnterpriseBasic = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, org.openide.util.NbBundle.getMessage(PanelShowListEnterprise.class, "PanelShowListEnterprise.jPanel1.border.title"), javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION)); // NOI18N

        jLabel2.setText(org.openide.util.NbBundle.getMessage(PanelShowListEnterprise.class, "PanelShowListEnterprise.jLabel2.text")); // NOI18N

        txtSearch.setText(org.openide.util.NbBundle.getMessage(PanelShowListEnterprise.class, "PanelShowListEnterprise.txtSearch.text")); // NOI18N
        txtSearch.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtSearchCaretUpdate(evt);
            }
        });

        jLabel3.setText(org.openide.util.NbBundle.getMessage(PanelShowListEnterprise.class, "PanelShowListEnterprise.jLabel3.text")); // NOI18N

        cbSearch.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbSearchItemStateChanged(evt);
            }
        });

        tableListEnterpriseBasic.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableListEnterpriseBasic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableListEnterpriseBasicMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableListEnterpriseBasic);

        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText(org.openide.util.NbBundle.getMessage(PanelShowListEnterprise.class, "PanelShowListEnterprise.jLabel4.text")); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText(org.openide.util.NbBundle.getMessage(PanelShowListEnterprise.class, "PanelShowListEnterprise.jLabel1.text")); // NOI18N
        jPanel2.add(jLabel1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 344, Short.MAX_VALUE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cbSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void tableListEnterpriseBasicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableListEnterpriseBasicMouseClicked

    try {
        BE_EnterpriseChoise = provider.getListInformation().get(tableListEnterpriseBasic.getSelectedRow());

    } catch (Exception e) {
        BE_EnterpriseChoise = null;
    }
    if (evt.getClickCount() < 2) {


        return;
    } else {
        ManagerPresentationEnterprise.getInstance().show(BE_EnterpriseChoise);
    }

}//GEN-LAST:event_tableListEnterpriseBasicMouseClicked
    //lay du lieu tu provider day len hien thi cb
private void cbSearchItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbSearchItemStateChanged

    searchData(txtSearch.getText(), cbSearch.getSelectedItem().toString().trim());
}//GEN-LAST:event_cbSearchItemStateChanged

private void txtSearchCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtSearchCaretUpdate
    if (!firstClick) {
        firstClick = true;
        txtSearch.setText("");
    }
    searchData(txtSearch.getText(), cbSearch.getSelectedItem().toString());
}//GEN-LAST:event_txtSearchCaretUpdate
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableListEnterpriseBasic;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    @Override
    public long getLevelPanelShowListEnterpriseBasic() {
        return LEVEL;
    }

    @Override
    public void setControlShowListInformation(IControlShowListInformation controlShowListInformation) {
        this.controlShowListInformation = controlShowListInformation;
    }

    @Override
    public void loadDataDefault() {
        txtSearch.setText("");
        loadTable();
    }

    @Override
    public void loadData(List<Long> listId) {
        if (listId != null) {
            provider.loaddListInformation(listId);
        } else {
            provider.loadAllInformation();
        }
        loadTable();
    }

    @Override
    public void searchData(String worldSearch, String typeSearch) {//tim kiem day du lieu tu provide len 
        provider.filterListInformation(typeSearch, worldSearch);
        loadTable();

    }

    private void loadTable() {
        ListEnterpriseTableModel model = new ListEnterpriseTableModel(provider.getListInformation());
        tableListEnterpriseBasic.setModel(model);
    }

    private void loadPopUp() {
//        if (hadLoadPopUp) {
//            return;
//        }
//        panelPopUp = new PanelPopUp();
//        for (int i = 0; i < panelShowEnterpriseBaiscs.size(); i++) {
//            final int k = i;
//            final JLabel lb = new JLabel(panelShowEnterpriseBaiscs.get(i).getDescriptionPanel());
//            lb.addMouseListener(new MouseAdapter() {
//
//                @Override
//                public void mouseClicked(MouseEvent e) {
//                    panelShowEnterpriseBaiscs.get(k).setEnterprise(enterpriseChoise);
//                    DialogInformation d =
//                            new DialogInformation((panelShowEnterpriseBaiscs.get(k)));
//                    d.setVisible(true);
//                }
//
//                @Override
//                public void mouseEntered(MouseEvent e) {
//                    lb.setForeground(Color.red);
//                }
//
//                @Override
//                public void mouseExited(MouseEvent e) {
//                    lb.setForeground(Color.black);
//                }
//            });
//            panelPopUp.add(lb);
//        }
//        popUpCommon = new PopUpCommon(panelPopUp);
//        hadLoadPopUp = true;
    }

    @Override
    public String toString() {
        return "Danh sách thông tin cơ bản của doanh nghiệp";
    }
}
