/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelShowPersonBasic.java
 *
 * Created on May 2, 2012, 1:50:20 PM
 */
package vn.com.hkt.em.basic.presentation.panel.show.spi;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JComboBox;
import org.openide.util.lookup.ServiceProvider;
import vn.com.hkt.em.basic.data.entities.Country;
import vn.com.hkt.em.basic.data.entities.Person;
import vn.com.hkt.em.basic.presentation.dialog.spi.CityDialog;
import vn.com.hkt.em.basic.presentation.panel.show.api.IPanelShowPersonBasic;
import vn.com.hkt.em.common.data.CheckData;
import vn.com.hkt.em.common.event.KeyControlPress;
import vn.com.hkt.em.common.image.ImageTool;

/**
 *
 * @author BinLe
 */
@ServiceProvider(service = IPanelShowPersonBasic.class)
public class PanelShowPersonBasic extends javax.swing.JPanel implements IPanelShowPersonBasic {

    private final long LEVEL = 1;// Level =1, đây là giao diện cha 
    //  private IProviderPanelShowPerson provider = new ProviderPanelShowPerson();//provider cung cấp dữ liệu cho giao diện
    // bắt sư kiện nhấn Controll    
    private KeyControlPress kl = new KeyControlPress();
    //Tool xử lý ảnh
    private ImageTool imageTool = new ImageTool();
    //chức năng hiện tại của giao diện là tạo mới hay xem,sửa,xóa (Mặc định là tạo mới)
    private int function = FUNCTION_CREATE;
    private CheckData checkData;

    /** Creates new form PanelShowPersonBasic */
    public PanelShowPersonBasic() {
        initComponents();
        checkData = new CheckData();
        setDefaultListener();
        loadDefault();
        resetData();
        function = FUNCTION_CREATE;
    }
 private class CTR_CLICK extends MouseAdapter {

        private JComboBox comboBox;

        public CTR_CLICK(JComboBox comboBox) {
            this.comboBox = comboBox;
        }

        @Override
        public void mouseClicked(MouseEvent e) {
            if (e.getClickCount() >= 2 && kl.isKeyCTRL()) {
                if (comboBox.equals(cbCity)) {
                    try {
                    //    Country c = (Country) cbCountry.getSelectedItem();
                        CityDialog cii = new CityDialog();
                      //  cii.setCountryFirst(c);
                        cii.setComboBox(cbCity);
                        cii.setVisible(true);
                    } catch (Exception ex) {
                        //loadComboboxCity();
                    }
                } else if (comboBox.equals(cbCountry)) {
                  //  CountryDialog coi = new CountryDialog();
                   // coi.setComboBox(comboBox);
                   // coi.setVisible(true);
                } else if (comboBox.equals(cbMaritalStatus)) {
                  //  MaritalStatusDialog msi = new MaritalStatusDialog();
                  //  msi.setComboBox(comboBox);
                  //  msi.setVisible(true);
                }
                kl.setKeyCTRL(false);
            }
        }
    }
    private void setDefaultListener() {
        cbCity.addKeyListener(kl);
        cbCity.addMouseListener(new CTR_CLICK(cbCity));
        
        cbCountry.addKeyListener(kl);
        cbCountry.addMouseListener(new CTR_CLICK(cbCountry) );
        
        cbMaritalStatus.addKeyListener(kl);
        cbMaritalStatus.addMouseListener(new CTR_CLICK(cbMaritalStatus));
       
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        lbDescription = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        cbMaritalStatus = new javax.swing.JComboBox();
        txtIdentityCard = new javax.swing.JTextField();
        lbMaritalStatus = new javax.swing.JLabel();
        lbIdentityCard = new javax.swing.JLabel();
        lbGender = new javax.swing.JLabel();
        dcBirthday = new com.toedter.calendar.JDateChooser();
        lbBirthday = new javax.swing.JLabel();
        txtGenderOther = new javax.swing.JTextField();
        rbtnGenderOther = new javax.swing.JRadioButton();
        rbtnGenderWomen = new javax.swing.JRadioButton();
        rbtnGenderMen = new javax.swing.JRadioButton();
        lbLastName = new javax.swing.JLabel();
        lbFirstName = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        txtFirstName = new javax.swing.JTextField();
        lbAddress = new javax.swing.JLabel();
        lbCity = new javax.swing.JLabel();
        cbCountry = new javax.swing.JComboBox();
        lbCiuntry = new javax.swing.JLabel();
        cbCity = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        lbMessenger = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lbImage = new javax.swing.JLabel();
        txtChildren = new javax.swing.JTextField();
        lbWeight = new javax.swing.JLabel();
        txtWeight = new javax.swing.JTextField();
        txtHeight = new javax.swing.JTextField();
        lbHeight = new javax.swing.JLabel();
        lbChildren = new javax.swing.JLabel();
        txtFax = new javax.swing.JTextField();
        lbWebsite = new javax.swing.JLabel();
        txtWebsite = new javax.swing.JTextField();
        txtMobile = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        lbEmail = new javax.swing.JLabel();
        txtTelephone = new javax.swing.JTextField();
        lbTelephone = new javax.swing.JLabel();
        lbMobile = new javax.swing.JLabel();
        lbFax = new javax.swing.JLabel();

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), org.openide.util.NbBundle.getMessage(PanelShowPersonBasic.class, "PanelShowPersonBasic.jPanel2.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        lbDescription.setText(org.openide.util.NbBundle.getMessage(PanelShowPersonBasic.class, "PanelShowPersonBasic.lbDescription.text")); // NOI18N

        txtDescription.setColumns(20);
        txtDescription.setRows(5);
        jScrollPane2.setViewportView(txtDescription);

        cbMaritalStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtIdentityCard.setText(org.openide.util.NbBundle.getMessage(PanelShowPersonBasic.class, "PanelShowPersonBasic.txtIdentityCard.text")); // NOI18N

        lbMaritalStatus.setText(org.openide.util.NbBundle.getMessage(PanelShowPersonBasic.class, "PanelShowPersonBasic.lbMaritalStatus.text")); // NOI18N

        lbIdentityCard.setText(org.openide.util.NbBundle.getMessage(PanelShowPersonBasic.class, "PanelShowPersonBasic.lbIdentityCard.text")); // NOI18N

        lbGender.setText(org.openide.util.NbBundle.getMessage(PanelShowPersonBasic.class, "PanelShowPersonBasic.lbGender.text")); // NOI18N

        dcBirthday.setDateFormatString(org.openide.util.NbBundle.getMessage(PanelShowPersonBasic.class, "PanelShowPersonBasic.dcBirthday.dateFormatString")); // NOI18N

        lbBirthday.setText(org.openide.util.NbBundle.getMessage(PanelShowPersonBasic.class, "PanelShowPersonBasic.lbBirthday.text")); // NOI18N

        txtGenderOther.setText(org.openide.util.NbBundle.getMessage(PanelShowPersonBasic.class, "PanelShowPersonBasic.txtGenderOther.text")); // NOI18N
        txtGenderOther.setEnabled(false);

        rbtnGenderOther.setText(org.openide.util.NbBundle.getMessage(PanelShowPersonBasic.class, "PanelShowPersonBasic.rbtnGenderOther.text")); // NOI18N

        rbtnGenderWomen.setText(org.openide.util.NbBundle.getMessage(PanelShowPersonBasic.class, "PanelShowPersonBasic.rbtnGenderWomen.text")); // NOI18N

        rbtnGenderMen.setSelected(true);
        rbtnGenderMen.setText(org.openide.util.NbBundle.getMessage(PanelShowPersonBasic.class, "PanelShowPersonBasic.rbtnGenderMen.text")); // NOI18N

        lbLastName.setText(org.openide.util.NbBundle.getMessage(PanelShowPersonBasic.class, "PanelShowPersonBasic.lbLastName.text")); // NOI18N

        lbFirstName.setText(org.openide.util.NbBundle.getMessage(PanelShowPersonBasic.class, "PanelShowPersonBasic.lbFirstName.text")); // NOI18N

        txtLastName.setText(org.openide.util.NbBundle.getMessage(PanelShowPersonBasic.class, "PanelShowPersonBasic.txtLastName.text")); // NOI18N

        txtFirstName.setText(org.openide.util.NbBundle.getMessage(PanelShowPersonBasic.class, "PanelShowPersonBasic.txtFirstName.text")); // NOI18N

        lbAddress.setText(org.openide.util.NbBundle.getMessage(PanelShowPersonBasic.class, "PanelShowPersonBasic.lbAddress.text")); // NOI18N

        lbCity.setText(org.openide.util.NbBundle.getMessage(PanelShowPersonBasic.class, "PanelShowPersonBasic.lbCity.text")); // NOI18N

        cbCountry.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lbCiuntry.setText(org.openide.util.NbBundle.getMessage(PanelShowPersonBasic.class, "PanelShowPersonBasic.lbCiuntry.text")); // NOI18N

        cbCity.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jScrollPane1.setViewportView(txtAddress);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbIdentityCard, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMaritalStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCity, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCiuntry, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbGender, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(cbMaritalStatus, 0, 158, Short.MAX_VALUE)
                        .addGap(0, 0, 0))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtLastName, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                        .addGap(0, 0, 0))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtIdentityCard, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                        .addGap(0, 0, 0))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                        .addGap(0, 0, 0))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(cbCountry, 0, 158, Short.MAX_VALUE)
                        .addGap(0, 0, 0))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(dcBirthday, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                        .addGap(0, 0, 0))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(cbCity, 0, 158, Short.MAX_VALUE)
                        .addGap(0, 0, 0))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(rbtnGenderOther)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtGenderOther, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(rbtnGenderMen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtnGenderWomen))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                        .addGap(0, 0, 0))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lbFirstName)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lbLastName)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(dcBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbBirthday))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lbGender)
                    .addComponent(rbtnGenderMen)
                    .addComponent(rbtnGenderWomen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnGenderOther)
                    .addComponent(txtGenderOther, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lbIdentityCard)
                    .addComponent(txtIdentityCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(cbMaritalStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMaritalStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(cbCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCiuntry))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lbCity)
                    .addComponent(cbCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbAddress)))
        );

        lbMessenger.setForeground(new java.awt.Color(255, 0, 0));
        lbMessenger.setText(org.openide.util.NbBundle.getMessage(PanelShowPersonBasic.class, "PanelShowPersonBasic.lbMessenger.text")); // NOI18N

        lbImage.setText(org.openide.util.NbBundle.getMessage(PanelShowPersonBasic.class, "PanelShowPersonBasic.lbImage.text")); // NOI18N
        lbImage.setBorder(javax.swing.BorderFactory.createTitledBorder(null, org.openide.util.NbBundle.getMessage(PanelShowPersonBasic.class, "PanelShowPersonBasic.lbImage.border.title"), javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION)); // NOI18N
        lbImage.setPreferredSize(new java.awt.Dimension(150, 100));
        jPanel1.add(lbImage);

        txtChildren.setText(org.openide.util.NbBundle.getMessage(PanelShowPersonBasic.class, "PanelShowPersonBasic.txtChildren.text")); // NOI18N

        lbWeight.setText(org.openide.util.NbBundle.getMessage(PanelShowPersonBasic.class, "PanelShowPersonBasic.lbWeight.text")); // NOI18N

        txtWeight.setText(org.openide.util.NbBundle.getMessage(PanelShowPersonBasic.class, "PanelShowPersonBasic.txtWeight.text")); // NOI18N

        txtHeight.setText(org.openide.util.NbBundle.getMessage(PanelShowPersonBasic.class, "PanelShowPersonBasic.txtHeight.text")); // NOI18N

        lbHeight.setText(org.openide.util.NbBundle.getMessage(PanelShowPersonBasic.class, "PanelShowPersonBasic.lbHeight.text")); // NOI18N

        lbChildren.setText(org.openide.util.NbBundle.getMessage(PanelShowPersonBasic.class, "PanelShowPersonBasic.lbChildren.text")); // NOI18N

        txtFax.setText(org.openide.util.NbBundle.getMessage(PanelShowPersonBasic.class, "PanelShowPersonBasic.txtFax.text")); // NOI18N

        lbWebsite.setText(org.openide.util.NbBundle.getMessage(PanelShowPersonBasic.class, "PanelShowPersonBasic.lbWebsite.text")); // NOI18N

        txtWebsite.setText(org.openide.util.NbBundle.getMessage(PanelShowPersonBasic.class, "PanelShowPersonBasic.txtWebsite.text")); // NOI18N

        txtMobile.setText(org.openide.util.NbBundle.getMessage(PanelShowPersonBasic.class, "PanelShowPersonBasic.txtMobile.text")); // NOI18N

        txtEmail.setText(org.openide.util.NbBundle.getMessage(PanelShowPersonBasic.class, "PanelShowPersonBasic.txtEmail.text")); // NOI18N

        lbEmail.setText(org.openide.util.NbBundle.getMessage(PanelShowPersonBasic.class, "PanelShowPersonBasic.lbEmail.text")); // NOI18N

        txtTelephone.setText(org.openide.util.NbBundle.getMessage(PanelShowPersonBasic.class, "PanelShowPersonBasic.txtTelephone.text")); // NOI18N

        lbTelephone.setText(org.openide.util.NbBundle.getMessage(PanelShowPersonBasic.class, "PanelShowPersonBasic.lbTelephone.text")); // NOI18N

        lbMobile.setText(org.openide.util.NbBundle.getMessage(PanelShowPersonBasic.class, "PanelShowPersonBasic.lbMobile.text")); // NOI18N

        lbFax.setText(org.openide.util.NbBundle.getMessage(PanelShowPersonBasic.class, "PanelShowPersonBasic.lbFax.text")); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbWebsite, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbChildren, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMobile, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbFax, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFax, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(txtWebsite, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(txtChildren, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(txtWeight, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(txtHeight, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(txtMobile, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(txtTelephone, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lbChildren)
                    .addComponent(txtChildren, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lbHeight)
                    .addComponent(txtHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lbWeight)
                    .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTelephone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMobile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lbFax))
                    .addComponent(txtFax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lbWebsite))
                    .addComponent(txtWebsite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lbEmail))
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(17, 17, 17)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(lbDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbMessenger, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lbDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbMessenger)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(31, 31, 31))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 549, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbCity;
    private javax.swing.JComboBox cbCountry;
    private javax.swing.JComboBox cbMaritalStatus;
    private com.toedter.calendar.JDateChooser dcBirthday;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbAddress;
    private javax.swing.JLabel lbBirthday;
    private javax.swing.JLabel lbChildren;
    private javax.swing.JLabel lbCity;
    private javax.swing.JLabel lbCiuntry;
    private javax.swing.JLabel lbDescription;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbFax;
    private javax.swing.JLabel lbFirstName;
    private javax.swing.JLabel lbGender;
    private javax.swing.JLabel lbHeight;
    private javax.swing.JLabel lbIdentityCard;
    private javax.swing.JLabel lbImage;
    private javax.swing.JLabel lbLastName;
    private javax.swing.JLabel lbMaritalStatus;
    private javax.swing.JLabel lbMessenger;
    private javax.swing.JLabel lbMobile;
    private javax.swing.JLabel lbTelephone;
    private javax.swing.JLabel lbWebsite;
    private javax.swing.JLabel lbWeight;
    private javax.swing.JRadioButton rbtnGenderMen;
    private javax.swing.JRadioButton rbtnGenderOther;
    private javax.swing.JRadioButton rbtnGenderWomen;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtChildren;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFax;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtGenderOther;
    private javax.swing.JTextField txtHeight;
    private javax.swing.JTextField txtIdentityCard;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtMobile;
    private javax.swing.JTextField txtTelephone;
    private javax.swing.JTextField txtWebsite;
    private javax.swing.JTextField txtWeight;
    // End of variables declaration//GEN-END:variables

    @Override
    public long getLevelPanelShowPersonBasic() {
        return LEVEL;
    }

    @Override
    public void setPersonShow(Person person) {
       //  provider.setDataView(person);
        refreshData();
        function = FUNCTION_EDIT;
    }

    @Override
    public String getDescriptionPanel() {
        return "Giao diện thông tin cơ bản cá nhân";
    }

    @Override
    public void resetData() {
      //   showEdit(true);
        txtAddress.setText("");
        txtDescription.setText("");
        txtEmail.setText("");
        txtFax.setText("");
        txtFirstName.setText("");
        rbtnGenderMen.setSelected(true);
        txtIdentityCard.setText("");
        txtLastName.setText("");
        txtMobile.setText("");
        txtTelephone.setText("");
        txtWebsite.setText("");
        txtHeight.setText("");
        txtWeight.setText("");
        txtChildren.setText("");
        dcBirthday.setDate(null);
      //  provider.setDataView(new Person());
        lbImage.setIcon(null);
        lbMessenger.setVisible(false);
        function=FUNCTION_CREATE;
    }

    @Override
    public long addData(long idParent) {
       return idParent;
    }
    @Override
    public void refreshData() {
        
    }

    @Override
    public void canEditData() {
      
    }

    @Override
    public long editData() {
       return editData();
    }

    @Override
    public long removeData() {
       return removeData();
    }

    @Override
    public int getFunction() {
        return function;
    }

    @Override
    public boolean checkData() {
       return true;
    }

    @Override
    public void loadDefault() {
    }
}
