/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelShowEnterpriseBusinessAreaDetails.java
 *
 * Created on May 14, 2012, 3:43:20 PM
 */
package vn.com.hkt.em.enterprise.presentation.panel.spi;

import java.util.ArrayList;
import java.util.List;
import org.openide.util.lookup.ServiceProvider;
import vn.com.hkt.em.basic.data.entities.Enterprise;
import vn.com.hkt.em.enterprise.business.provider.panel.api.IProviderPanelShowEnterpriseBusinessArea;
import vn.com.hkt.em.enterprise.business.provider.panel.spi.ProviderPanelShowEnterpriseBusinessArea;
import vn.com.hkt.em.enterprise.data.entities.EnterpriseBusinessArea;
import vn.com.hkt.em.enterprise.presentation.panel.api.IPanelShowEnterpriseBusinessArea;
import vn.com.hkt.em.enterprise.presentation.panel.spi.table.model.TableModelEnterpriseBusinessArea;

/**
 *
 * @author duong
 */
@ServiceProvider(service = IPanelShowEnterpriseBusinessArea.class)
public class PanelShowEnterpriseBusinessAreaDetails extends javax.swing.JPanel implements IPanelShowEnterpriseBusinessArea {

    /** Creates new form PanelShowEnterpriseBusinessAreaDetails */
    private IProviderPanelShowEnterpriseBusinessArea provider = new ProviderPanelShowEnterpriseBusinessArea();
    private int function;
    private long LEVLE_ENTERPRISE_BUSINESS_AREA = 1;
    private TableModelEnterpriseBusinessArea tableModelEnterpriseBusinessArea;        

    public PanelShowEnterpriseBusinessAreaDetails() {
        initComponents();
        resetData();
      
    }

    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableBusinessArea = new javax.swing.JTable();

        tableBusinessArea.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableBusinessArea);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableBusinessArea;
    // End of variables declaration//GEN-END:variables

    @Override
    public long getLevelPanelShowEnterpriseBusinessArea() {
        return LEVLE_ENTERPRISE_BUSINESS_AREA;
    }

    @Override
    public void setEnterpriseBusinessAreas(List<EnterpriseBusinessArea> enterpriseBusinessAreas) {
        loadTable();
    }

    private void loadTable() {
        //  tableModelEnterpriseBusinessArea= new TableModelEnterpriseBusinessArea();

            tableModelEnterpriseBusinessArea = new TableModelEnterpriseBusinessArea(provider.getEnterpriseBusinessAreas());
            tableBusinessArea.setModel(tableModelEnterpriseBusinessArea);            
      

    }

    @Override
    public List<EnterpriseBusinessArea> getEnterpriseBusinessAreas() {
       // return null;
         return provider.getEnterpriseBusinessAreas();
    }

    @Override
    public void setEnterprise(Enterprise enterprise) {
        // provider.setDataView(enterprise);
        function = FUNCTION_EDIT;
        refreshData();
    }

    @Override
    public Enterprise getEnterprise() {
        return provider.getDataViewCurrent();
    }

    @Override
    public String getDescriptionPanel() {
        return "Lĩnh vực kinh doanh";
    }

    @Override
    public void resetData() {
        //tap ra 1 mang moi de hien thi
       provider.setEnterpriseBusinessAreas(new ArrayList<EnterpriseBusinessArea>());
        loadTable();
    }

    @Override
    public long addData(long idParent) {
        return idParent;
    }

    @Override
    public void refreshData() {
        // provider.refreshData();
        loadTable();
    }

    @Override
    public void canEditData() {
    }

    @Override
    public long editData() {
        return 0;
    }

    @Override
    public long removeData() {
        return removeData();
    }

    @Override
    public int getFunction() {
        return function;
    }

    @Override
    public boolean checkData() {
        return true;
    }

    @Override
    public void loadDefault() {
        loadTable();
    }
}
