/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelShowEnterpriseAddressDetails.java
 *
 * Created on May 16, 2012, 10:28:02 AM
 */
package vn.com.hkt.em.enterprise.presentation.panel.spi;

import java.util.ArrayList;
import java.util.List;
import vn.com.hkt.em.basic.data.entities.Enterprise;
import vn.com.hkt.em.enterprise.business.provider.panel.api.IProviderPanelShowEnterpriseAddress;
import vn.com.hkt.em.enterprise.business.provider.panel.spi.ProviderPanelShowEnterpriseAddress;
import vn.com.hkt.em.enterprise.data.entities.EnterpriseAddress;
import vn.com.hkt.em.enterprise.presentation.panel.api.IPanelShowEnterpriseAddress;
import vn.com.hkt.em.enterprise.presentation.panel.spi.table.model.TableModelEnterpriseAddress;

/**
 *
 * @author duong
 */
public class PanelShowEnterpriseAddressDetails extends javax.swing.JPanel implements IPanelShowEnterpriseAddress {

    private final long LEVEL_ENTERPRISE_ADDRESS = 1;
    private IProviderPanelShowEnterpriseAddress provider = new ProviderPanelShowEnterpriseAddress();
    private int function = FUNCTION_CREATE;
    private final long LEVEL_ENTERPRISE_BASIC = 4;
    private TableModelEnterpriseAddress model;
    /** Creates new form PanelShowEnterpriseAddressDetails */
    public PanelShowEnterpriseAddressDetails() {
        initComponents();
        resetData();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAddress = new javax.swing.JTable();

        jScrollPane1.setBorder(null);

        tableAddress.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableAddress);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableAddress;
    // End of variables declaration//GEN-END:variables

    @Override
    public long getLevelPanelShowEnterpriseAddress() {
       return LEVEL_ENTERPRISE_ADDRESS;
    }

    @Override
    public void setEnterpriseAddresses(List<EnterpriseAddress> enterpriseAddresses) {
       provider.setEnterpriseAddresses(enterpriseAddresses);
        loadTable();
    }

    @Override
    public List<EnterpriseAddress> getEnterpriseAddresses() {
     return provider.getEnterpriseAddresses();
    }

    @Override
    public void setEnterprise(Enterprise enterprise) {
         provider.setDataView(enterprise);
        function = FUNCTION_EDIT;
        refreshData();
    }

    @Override
    public Enterprise getEnterprise() {
         return provider.getDataViewCurrent();
    }

    @Override
    public String getDescriptionPanel() {
       return "Địa chỉ doanh nghiệp";
    }

    @Override
    public void resetData() {
        provider.setEnterpriseAddresses(new ArrayList<EnterpriseAddress>());
        loadTable();
    }

    @Override
    public long addData(long idParent) {
      return idParent;
    }

    @Override
    public void refreshData() {
        
    }

    @Override
    public void canEditData() {
       
    }

    @Override
    public long editData() {
     return 0;
    }

    @Override
    public long removeData() {
      return removeData();
    }

    @Override
    public int getFunction() {
        return function;
    }

    @Override
    public boolean checkData() {
       return true;
    }

    @Override
    public void loadDefault() {
       loadTable();
    }

    private void loadTable() {
        model = new TableModelEnterpriseAddress(provider.getEnterpriseAddresses());
        tableAddress.setModel(model);
    }
}
