/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelShowEnterpriseLegalDetails.java
 *
 * Created on May 11, 2012, 4:03:29 PM
 */
package vn.com.hkt.em.enterprise.presentation.panel.spi;

import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.event.CaretEvent;
import javax.swing.event.CaretListener;
import org.openide.util.lookup.ServiceProvider;
import vn.com.hkt.em.basic.data.entities.Enterprise;
import vn.com.hkt.em.basic.data.entities.Person;
import vn.com.hkt.em.common.data.CheckData;
import vn.com.hkt.em.common.event.KeyControlPress;
import vn.com.hkt.em.enterprise.business.provider.panel.api.IProviderPanelShowEnterpriseLegal;
import vn.com.hkt.em.enterprise.business.provider.panel.spi.ProviderPanelShowEnterpriseLegal;
import vn.com.hkt.em.enterprise.data.entities.EnterpriseLegal;
import vn.com.hkt.em.enterprise.data.entities.EnterpriseType;
import vn.com.hkt.em.enterprise.presentation.dialog.spi.DialogEnterpriseType;
import vn.com.hkt.em.enterprise.presentation.panel.api.IPanelShowEnterpriseLegal;

/**
 *
 * @author duong
 */
@ServiceProvider(service = IPanelShowEnterpriseLegal.class)
public class PanelShowEnterpriseLegalDetails extends javax.swing.JPanel implements IPanelShowEnterpriseLegal {

    private final long LEVEL_ENTERPRISE_LEGAL = 1;
    private KeyControlPress kl = new KeyControlPress();
    private int function;
    private IProviderPanelShowEnterpriseLegal provider = new ProviderPanelShowEnterpriseLegal();
    private CheckData checkData = new CheckData();
    private long idEnterpriseTypeChoise;

    /** Creates new form PanelShowEnterpriseLegalDetails */
    public PanelShowEnterpriseLegalDetails() {
        initComponents();
        function = FUNCTION_CREATE;
        resetData();
        loadComboBox();
        loadListener();
    }

    private void loadListener() {
        cbEnterpriseType.addKeyListener(kl);
        cbEnterpriseType.addMouseListener(new CTR_CLICK(cbEnterpriseType));
        setDefaultListenerDateChooser();
    }

    private void setDefaultListenerDateChooser() {
        ((JTextField) dcDateEstablishment.getDateEditor().getUiComponent()).addCaretListener(new CaretListener() {

            @Override
            public void caretUpdate(CaretEvent e) {
                if (((JTextField) dcDateEstablishment.getDateEditor().getUiComponent()).getText().isEmpty()) {
                    lbDateEstablishment.setForeground(Color.black);
                    return;
                }
                try {
                    Date date = dcDateEstablishment.getDate();
                    if (date == null) {
                        lbDateEstablishment.setForeground(Color.red);
                    } else {
                        lbDateEstablishment.setForeground(Color.black);
                    }
                } catch (Exception ex) {
                    lbDateEstablishment.setForeground(Color.red);
                }
            }
        });

        //lay dl  dcDateRegistration khi thay doi datepicker
        ((JTextField) dcDateRegistration.getDateEditor().getUiComponent()).addCaretListener(new CaretListener() {

            @Override
            public void caretUpdate(CaretEvent e) {
                if (((JTextField) dcDateRegistration.getDateEditor().getUiComponent()).getText().isEmpty()) {
                    lbDateRegistration.setForeground(Color.black);
                    return;
                }
                try {
                    Date date = dcDateRegistration.getDate();
                    if (date == null) {
                        lbDateRegistration.setForeground(Color.red);
                    } else {
                        lbDateRegistration.setForeground(Color.black);
                    }
                } catch (Exception ex) {
                    lbDateRegistration.setForeground(Color.red);
                }
            }
        });

    }

    private class CTR_CLICK extends MouseAdapter {

        private JComboBox comboBox;

        public CTR_CLICK(JComboBox comboBox) {
            this.comboBox = comboBox;
        }

        @Override
        public void mouseClicked(MouseEvent e) {
            if (e.getClickCount() >= 2 && kl.isKeyCTRL()) {
                if (comboBox.equals(cbEnterpriseType)) {
                    DialogEnterpriseType dialog = new DialogEnterpriseType();
                    dialog.setComboBox(comboBox);
                    dialog.setVisible(true);
                }
                kl.setKeyCTRL(false);
            }
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbEnterpriseNameEnglish = new javax.swing.JLabel();
        lbEnterpriseNameVN = new javax.swing.JLabel();
        txtEnterpriseNameVN = new javax.swing.JTextField();
        lbEnterpriseName = new javax.swing.JLabel();
        txtEnterpriseName = new javax.swing.JTextField();
        lbDateEstablishment = new javax.swing.JLabel();
        lbDateRegistration = new javax.swing.JLabel();
        dcDateEstablishment = new com.toedter.calendar.JDateChooser();
        dcDateRegistration = new com.toedter.calendar.JDateChooser();
        lbBusinessRegistrationTime = new javax.swing.JLabel();
        txtBusinessRegistrationTime = new javax.swing.JTextField();
        txtEnterpriseNameEnglish = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        lbResponsibleLegal = new javax.swing.JLabel();
        cbEnterpriseType = new javax.swing.JComboBox();
        txtTaxCodeNumber = new javax.swing.JTextField();
        txtCharteredCapital = new javax.swing.JTextField();
        lbLegalCapital = new javax.swing.JLabel();
        lbCharteredCapital = new javax.swing.JLabel();
        txtLegalCapital = new javax.swing.JTextField();
        lbEnterpriseType = new javax.swing.JLabel();
        cbResponsibleLegal = new javax.swing.JComboBox();
        txtBusinessResgitrationNumber = new javax.swing.JTextField();
        lbTaxCodeNumber = new javax.swing.JLabel();
        lbBusinessResgitrationNumber = new javax.swing.JLabel();
        lbMessenger = new javax.swing.JLabel();

        lbEnterpriseNameEnglish.setText(org.openide.util.NbBundle.getMessage(PanelShowEnterpriseLegalDetails.class, "PanelShowEnterpriseLegalDetails.lbEnterpriseNameEnglish.text")); // NOI18N

        lbEnterpriseNameVN.setText(org.openide.util.NbBundle.getMessage(PanelShowEnterpriseLegalDetails.class, "PanelShowEnterpriseLegalDetails.lbEnterpriseNameVN.text")); // NOI18N

        txtEnterpriseNameVN.setText(org.openide.util.NbBundle.getMessage(PanelShowEnterpriseLegalDetails.class, "PanelShowEnterpriseLegalDetails.txtEnterpriseNameVN.text")); // NOI18N

        lbEnterpriseName.setText(org.openide.util.NbBundle.getMessage(PanelShowEnterpriseLegalDetails.class, "PanelShowEnterpriseLegalDetails.lbEnterpriseName.text")); // NOI18N

        txtEnterpriseName.setEditable(false);
        txtEnterpriseName.setText(org.openide.util.NbBundle.getMessage(PanelShowEnterpriseLegalDetails.class, "PanelShowEnterpriseLegalDetails.txtEnterpriseName.text")); // NOI18N
        txtEnterpriseName.setToolTipText(org.openide.util.NbBundle.getMessage(PanelShowEnterpriseLegalDetails.class, "PanelShowEnterpriseLegalDetails.txtEnterpriseName.toolTipText")); // NOI18N

        lbDateEstablishment.setText(org.openide.util.NbBundle.getMessage(PanelShowEnterpriseLegalDetails.class, "PanelShowEnterpriseLegalDetails.lbDateEstablishment.text")); // NOI18N

        lbDateRegistration.setText(org.openide.util.NbBundle.getMessage(PanelShowEnterpriseLegalDetails.class, "PanelShowEnterpriseLegalDetails.lbDateRegistration.text")); // NOI18N

        dcDateEstablishment.setDateFormatString(org.openide.util.NbBundle.getMessage(PanelShowEnterpriseLegalDetails.class, "PanelShowEnterpriseLegalDetails.dcDateEstablishment.dateFormatString")); // NOI18N

        dcDateRegistration.setDateFormatString(org.openide.util.NbBundle.getMessage(PanelShowEnterpriseLegalDetails.class, "PanelShowEnterpriseLegalDetails.dcDateRegistration.dateFormatString")); // NOI18N

        lbBusinessRegistrationTime.setText(org.openide.util.NbBundle.getMessage(PanelShowEnterpriseLegalDetails.class, "PanelShowEnterpriseLegalDetails.lbBusinessRegistrationTime.text")); // NOI18N

        txtBusinessRegistrationTime.setText(org.openide.util.NbBundle.getMessage(PanelShowEnterpriseLegalDetails.class, "PanelShowEnterpriseLegalDetails.txtBusinessRegistrationTime.text")); // NOI18N

        txtEnterpriseNameEnglish.setText(org.openide.util.NbBundle.getMessage(PanelShowEnterpriseLegalDetails.class, "PanelShowEnterpriseLegalDetails.txtEnterpriseNameEnglish.text")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbEnterpriseNameEnglish, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEnterpriseNameVN, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEnterpriseName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDateEstablishment, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDateRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbBusinessRegistrationTime, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEnterpriseNameVN, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                    .addComponent(txtEnterpriseName, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                    .addComponent(dcDateEstablishment, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                    .addComponent(dcDateRegistration, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                    .addComponent(txtBusinessRegistrationTime, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                    .addComponent(txtEnterpriseNameEnglish, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lbEnterpriseName))
                    .addComponent(txtEnterpriseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lbEnterpriseNameVN))
                    .addComponent(txtEnterpriseNameVN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lbEnterpriseNameEnglish))
                    .addComponent(txtEnterpriseNameEnglish, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lbDateRegistration))
                    .addComponent(dcDateRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lbDateEstablishment))
                    .addComponent(dcDateEstablishment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lbBusinessRegistrationTime))
                    .addComponent(txtBusinessRegistrationTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        lbResponsibleLegal.setText(org.openide.util.NbBundle.getMessage(PanelShowEnterpriseLegalDetails.class, "PanelShowEnterpriseLegalDetails.lbResponsibleLegal.text")); // NOI18N

        txtTaxCodeNumber.setText(org.openide.util.NbBundle.getMessage(PanelShowEnterpriseLegalDetails.class, "PanelShowEnterpriseLegalDetails.txtTaxCodeNumber.text")); // NOI18N

        txtCharteredCapital.setText(org.openide.util.NbBundle.getMessage(PanelShowEnterpriseLegalDetails.class, "PanelShowEnterpriseLegalDetails.txtCharteredCapital.text")); // NOI18N

        lbLegalCapital.setText(org.openide.util.NbBundle.getMessage(PanelShowEnterpriseLegalDetails.class, "PanelShowEnterpriseLegalDetails.lbLegalCapital.text")); // NOI18N

        lbCharteredCapital.setText(org.openide.util.NbBundle.getMessage(PanelShowEnterpriseLegalDetails.class, "PanelShowEnterpriseLegalDetails.lbCharteredCapital.text")); // NOI18N

        txtLegalCapital.setText(org.openide.util.NbBundle.getMessage(PanelShowEnterpriseLegalDetails.class, "PanelShowEnterpriseLegalDetails.txtLegalCapital.text")); // NOI18N

        lbEnterpriseType.setText(org.openide.util.NbBundle.getMessage(PanelShowEnterpriseLegalDetails.class, "PanelShowEnterpriseLegalDetails.lbEnterpriseType.text")); // NOI18N

        txtBusinessResgitrationNumber.setText(org.openide.util.NbBundle.getMessage(PanelShowEnterpriseLegalDetails.class, "PanelShowEnterpriseLegalDetails.txtBusinessResgitrationNumber.text")); // NOI18N

        lbTaxCodeNumber.setText(org.openide.util.NbBundle.getMessage(PanelShowEnterpriseLegalDetails.class, "PanelShowEnterpriseLegalDetails.lbTaxCodeNumber.text")); // NOI18N

        lbBusinessResgitrationNumber.setText(org.openide.util.NbBundle.getMessage(PanelShowEnterpriseLegalDetails.class, "PanelShowEnterpriseLegalDetails.lbBusinessResgitrationNumber.text")); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbResponsibleLegal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbLegalCapital, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCharteredCapital, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEnterpriseType, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTaxCodeNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbBusinessResgitrationNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbEnterpriseType, 0, 139, Short.MAX_VALUE)
                    .addComponent(txtTaxCodeNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addComponent(txtCharteredCapital, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addComponent(txtLegalCapital, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addComponent(cbResponsibleLegal, 0, 139, Short.MAX_VALUE)
                    .addComponent(txtBusinessResgitrationNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lbEnterpriseType))
                    .addComponent(cbEnterpriseType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lbResponsibleLegal))
                    .addComponent(cbResponsibleLegal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lbCharteredCapital))
                    .addComponent(txtCharteredCapital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lbLegalCapital))
                    .addComponent(txtLegalCapital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lbBusinessResgitrationNumber))
                    .addComponent(txtBusinessResgitrationNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lbTaxCodeNumber))
                    .addComponent(txtTaxCodeNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbMessenger.setForeground(new java.awt.Color(255, 0, 0));
        lbMessenger.setText(org.openide.util.NbBundle.getMessage(PanelShowEnterpriseLegalDetails.class, "PanelShowEnterpriseLegalDetails.lbMessenger.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbMessenger, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(lbMessenger))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void checkComboBoxEnterpriseType() {
        if (!(cbEnterpriseType.getSelectedItem() instanceof EnterpriseType)) {
            lbEnterpriseType.setForeground(Color.red);
            idEnterpriseTypeChoise = 0;
        } else {
            lbEnterpriseType.setForeground(Color.black);
            idEnterpriseTypeChoise = ((EnterpriseType) cbEnterpriseType.getSelectedItem()).getId();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbEnterpriseType;
    private javax.swing.JComboBox cbResponsibleLegal;
    private com.toedter.calendar.JDateChooser dcDateEstablishment;
    private com.toedter.calendar.JDateChooser dcDateRegistration;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbBusinessRegistrationTime;
    private javax.swing.JLabel lbBusinessResgitrationNumber;
    private javax.swing.JLabel lbCharteredCapital;
    private javax.swing.JLabel lbDateEstablishment;
    private javax.swing.JLabel lbDateRegistration;
    private javax.swing.JLabel lbEnterpriseName;
    private javax.swing.JLabel lbEnterpriseNameEnglish;
    private javax.swing.JLabel lbEnterpriseNameVN;
    private javax.swing.JLabel lbEnterpriseType;
    private javax.swing.JLabel lbLegalCapital;
    private javax.swing.JLabel lbMessenger;
    private javax.swing.JLabel lbResponsibleLegal;
    private javax.swing.JLabel lbTaxCodeNumber;
    private javax.swing.JTextField txtBusinessRegistrationTime;
    private javax.swing.JTextField txtBusinessResgitrationNumber;
    private javax.swing.JTextField txtCharteredCapital;
    private javax.swing.JTextField txtEnterpriseName;
    private javax.swing.JTextField txtEnterpriseNameEnglish;
    private javax.swing.JTextField txtEnterpriseNameVN;
    private javax.swing.JTextField txtLegalCapital;
    private javax.swing.JTextField txtTaxCodeNumber;
    // End of variables declaration//GEN-END:variables

    @Override
    public long getLevelPanelShowEnterpriseLegal() {
        return LEVEL_ENTERPRISE_LEGAL;
    }

    @Override
    public void setEnterpriseLegal(EnterpriseLegal enterpriseLegal) {
        provider.setDataView(enterpriseLegal);
        refreshData();
        function = FUNCTION_EDIT;
    }

    @Override
    public EnterpriseLegal getEnterpriseLegal() {
        return provider.getDataViewCurrent();
    }

    @Override
    public void setEnterprise(Enterprise enterprise) {
        provider.setEnterprise(enterprise);
        refreshData();
    }

    @Override
    public Enterprise getEnterprise() {
        return null;
    }

    @Override
    public String getDescriptionPanel() {
        return "Thông tin pháp lý";
    }

    @Override
    public void resetData() {
        showEdit(true);
        provider.setEnterprise(new Enterprise());
        txtBusinessRegistrationTime.setText("");
        txtBusinessResgitrationNumber.setText("");
        txtCharteredCapital.setText("");
        txtEnterpriseName.setText(provider.getEnterpriseName());
        txtEnterpriseNameEnglish.setText("");
        txtEnterpriseNameVN.setText("");
        txtLegalCapital.setText("");
        txtTaxCodeNumber.setText("");
        lbMessenger.setVisible(false);
    }

    private void showEdit(boolean edit) {
        txtBusinessRegistrationTime.setEnabled(edit);
        txtBusinessResgitrationNumber.setEnabled(edit);
        txtCharteredCapital.setEnabled(edit);
        txtEnterpriseNameEnglish.setEnabled(edit);
        txtEnterpriseNameVN.setEnabled(edit);
        txtLegalCapital.setEnabled(edit);
        txtTaxCodeNumber.setEnabled(edit);
        dcDateEstablishment.setEnabled(edit);
        dcDateRegistration.setEnabled(edit);
        cbEnterpriseType.setEnabled(edit);
        cbResponsibleLegal.setEnabled(edit);
    }

    private boolean getData() { // truyen dl tu txt xuong table
        if (!checkData()) {
            return false;
        }
        provider.getDataViewCurrent().setEnterpriseNameVietNam(txtEnterpriseNameVN.getText());
        provider.getDataViewCurrent().setEnterpriseNameEnglish(txtEnterpriseNameEnglish.getText());
        provider.getDataViewCurrent().setDateEstablishment(dcDateEstablishment.getDate());
        provider.getDataViewCurrent().setDateRegistration(dcDateRegistration.getDate());
        provider.getDataViewCurrent().setBusinessRegistrationTime(txtBusinessRegistrationTime.getText());
        try {
            EnterpriseType enterpriseType = (EnterpriseType) cbEnterpriseType.getSelectedItem();
            provider.getDataViewCurrent().setIdEnterpriseType(enterpriseType.getId());
        } catch (Exception e) {
            provider.getDataViewCurrent().setIdEnterpriseType(0);
        }
        try {
            Person person = (Person) cbResponsibleLegal.getSelectedItem();
            provider.getDataViewCurrent().setIdPersonResponsibleLegal(person.getId());
        } catch (Exception e) {
            provider.getDataViewCurrent().setIdPersonResponsibleLegal(0);
        }
        try {
            provider.getDataViewCurrent().setCharteredCapital(Float.valueOf(txtCharteredCapital.getText()));
        } catch (Exception e) {
            provider.getDataViewCurrent().setCharteredCapital(0);
        }
        try {
            provider.getDataViewCurrent().setLegalCapital(Float.valueOf(txtLegalCapital.getText()));
        } catch (Exception e) {
            provider.getDataViewCurrent().setLegalCapital(0);
        }
        provider.getDataViewCurrent().setBusinessResgitrationNumber(txtBusinessResgitrationNumber.getText());
        provider.getDataViewCurrent().setTaxCodeNumber(txtTaxCodeNumber.getText());
        return true;
    }

    @Override
    public long addData(long idParent) {
        if (!getData()) {
            return ID_FAILD;
        }
        long id = provider.addData(idParent);
        if (id < 0) {
            return ID_FAILD;
        } else {
            lbMessenger.setVisible(false);
            return id;
        }

    }

    @Override
    public void refreshData() { //hien thi len txt
        provider.refreshData();
        txtEnterpriseName.setText(provider.getEnterpriseName()); // lay ten da co hien thi len 
        txtBusinessRegistrationTime.setText(provider.getDataViewCurrent().getBusinessRegistrationTime());
        txtBusinessResgitrationNumber.setText(provider.getDataViewCurrent().getBusinessResgitrationNumber());
        txtCharteredCapital.setText(String.valueOf(provider.getDataViewCurrent().getCharteredCapital()));
        txtEnterpriseName.setText(provider.getEnterpriseName());
        txtEnterpriseNameEnglish.setText(provider.getDataViewCurrent().getEnterpriseNameEnglish());
        txtEnterpriseNameVN.setText(provider.getDataViewCurrent().getEnterpriseNameVietNam());
        txtLegalCapital.setText(String.valueOf(provider.getDataViewCurrent().getLegalCapital()));
        txtTaxCodeNumber.setText(provider.getDataViewCurrent().getTaxCodeNumber());
        dcDateEstablishment.setDate(provider.getDataViewCurrent().getDateEstablishment());
        dcDateRegistration.setDate(provider.getDataViewCurrent().getDateRegistration());
        loadComboBox();
        for (int i = 0; i < cbEnterpriseType.getItemCount(); i++) {
            try {
                EnterpriseType enterpriseType = (EnterpriseType) cbEnterpriseType.getItemAt(i);
                if (enterpriseType.getId() == provider.getDataViewCurrent().getIdEnterpriseType()) {
                    cbEnterpriseType.setSelectedIndex(i);
                    break;
                }
            } catch (Exception e) {
            }
        }
        for (int i = 0; i < cbResponsibleLegal.getItemCount(); i++) {
            try {
                Person person = (Person) cbResponsibleLegal.getItemAt(i);
                if (person.getId() == provider.getDataViewCurrent().getIdPersonResponsibleLegal()) {
                    cbResponsibleLegal.setSelectedIndex(i);
                    break;
                }
            } catch (Exception e) {
            }
        }
        showEdit(false);
    }

    @Override
    public void canEditData() {
        showEdit(true);
    }

    @Override
    public long editData() { // chinh sua
        if (!getData()) {
            return ID_FAILD;
        } else {
            long id = provider.editData();
            if (id < 0) {
                return ID_FAILD;
            } else {
                lbMessenger.setVisible(false);
                return id;
            }
        }
    }

    @Override
    public long removeData() {
        long id = provider.getDataViewCurrent().getId();
        if (provider.removeData() < 0) {
            return ID_FAILD;
        } else {
            lbMessenger.setVisible(false);
            return id;
        }

    }

    @Override
    public int getFunction() {
        return function;
    }

    @Override
    public boolean checkData() {
        if (lbBusinessRegistrationTime.getForeground().equals(Color.red)
                || lbBusinessResgitrationNumber.getForeground().equals(Color.red)
                || lbCharteredCapital.getForeground().equals(Color.red)
                || lbDateEstablishment.getForeground().equals(Color.red)
                || lbDateRegistration.getForeground().equals(Color.red)
                || lbLegalCapital.getForeground().equals(Color.red)
                || lbTaxCodeNumber.getForeground().equals(Color.red)) {
            lbMessenger.setVisible(true);
            lbMessenger.setText("Hãy chú ý dữ liệu những phần bị đỏ");
            return false;
        }
        lbMessenger.setVisible(false);
        return true;
    }

    @Override
    public void loadDefault() {
    }

    private void loadComboBox() {
        List<EnterpriseType> enterpriseTypes = provider.getEnterpriseTypes();
        cbEnterpriseType.setModel(new DefaultComboBoxModel(enterpriseTypes.toArray()));

        List<Person> persons = provider.getPersons();
        cbResponsibleLegal.setModel(new DefaultComboBoxModel(persons.toArray()));
    }
}
