/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * InformationPanel.java
 *
 * Created on Apr 4, 2012, 2:15:06 PM
 */
package vn.com.hkt.em.common.gui.panel.control.function.spi;

import vn.com.hkt.em.common.gui.panel.control.function.api.IPanelControlFunctionTotal;
import vn.com.hkt.em.common.gui.panel.controlshow.spi.PanelControlShowInformation;
import vn.com.hkt.em.common.gui.topcomponent.spi.EnterpriseManagerTopComponent;

/**
 * Giao diện điều khiển chức năng hiển thị thông tin
 * @author BinLe
 */
public class PanelControlFunctionInformation extends javax.swing.JPanel implements IPanelControlFunctionTotal {

    private EnterpriseManagerTopComponent topComponent;// topcomponent hiển thị
    private PanelControlShowInformation panelControlShowInformation;// giao diện điều khiển hiển thị thông tin

    /** Creates new form InformationPanel */
    public PanelControlFunctionInformation(PanelControlShowInformation panelControlShowInformation) {
        initComponents();
        this.panelControlShowInformation = panelControlShowInformation;
        scrollPane.setViewportView(panelControlShowInformation);
        showButton();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnReset = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnCanEdit = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHelp = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnPanelInformation = new javax.swing.JButton();
        scrollPane = new javax.swing.JScrollPane();

        btnReset.setText(org.openide.util.NbBundle.getMessage(PanelControlFunctionInformation.class, "PanelControlFunctionInformation.btnReset.text")); // NOI18N
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnAdd.setText(org.openide.util.NbBundle.getMessage(PanelControlFunctionInformation.class, "PanelControlFunctionInformation.btnAdd.text")); // NOI18N
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnCanEdit.setText(org.openide.util.NbBundle.getMessage(PanelControlFunctionInformation.class, "PanelControlFunctionInformation.btnCanEdit.text")); // NOI18N
        btnCanEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCanEditActionPerformed(evt);
            }
        });

        btnEdit.setText(org.openide.util.NbBundle.getMessage(PanelControlFunctionInformation.class, "PanelControlFunctionInformation.btnEdit.text")); // NOI18N
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnHelp.setText(org.openide.util.NbBundle.getMessage(PanelControlFunctionInformation.class, "PanelControlFunctionInformation.btnHelp.text")); // NOI18N
        btnHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpActionPerformed(evt);
            }
        });

        btnRemove.setText(org.openide.util.NbBundle.getMessage(PanelControlFunctionInformation.class, "PanelControlFunctionInformation.btnRemove.text")); // NOI18N
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        btnClose.setText(org.openide.util.NbBundle.getMessage(PanelControlFunctionInformation.class, "PanelControlFunctionInformation.btnClose.text")); // NOI18N
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnRefresh.setText(org.openide.util.NbBundle.getMessage(PanelControlFunctionInformation.class, "PanelControlFunctionInformation.btnRefresh.text")); // NOI18N
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnPanelInformation.setText(org.openide.util.NbBundle.getMessage(PanelControlFunctionInformation.class, "PanelControlFunctionInformation.btnPanelInformation.text")); // NOI18N
        btnPanelInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPanelInformationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPanelInformation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReset)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdd)
                .addGap(6, 6, 6)
                .addComponent(btnRefresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCanEdit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEdit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRemove)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHelp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClose))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnHelp)
                .addComponent(btnClose)
                .addComponent(btnReset)
                .addComponent(btnAdd)
                .addComponent(btnCanEdit)
                .addComponent(btnEdit)
                .addComponent(btnRemove)
                .addComponent(btnRefresh)
                .addComponent(btnPanelInformation))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 687, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        panelControlShowInformation.resetData();
        buttonCreater();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        panelControlShowInformation.addData();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnCanEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCanEditActionPerformed
        btnEdit.setEnabled(true);
        btnRemove.setEnabled(true);
        panelControlShowInformation.canEditData();
    }//GEN-LAST:event_btnCanEditActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        if (panelControlShowInformation.editData()) {
            buttonCreater();
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        panelControlShowInformation.removeData();
        buttonCreater();
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpActionPerformed
        //TODO chu co help
//        information.help();
    }//GEN-LAST:event_btnHelpActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        topComponent.close();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        panelControlShowInformation.refreshData();
        showButton();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnPanelInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPanelInformationActionPerformed
        panelControlShowInformation.processPanelInformation();
    }//GEN-LAST:event_btnPanelInformationActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCanEdit;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHelp;
    private javax.swing.JButton btnPanelInformation;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnReset;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables

    /**
     * điều khiển các button chức năng
     */
    public void showButton() {
        if (panelControlShowInformation.getFunction() == PanelControlShowInformation.FUNCTION_CREATE) {
            buttonCreater();
        } else if (panelControlShowInformation.getFunction() == PanelControlShowInformation.FUNCTION_EDIT) {
            buttonShow();
        }
    }

    /**
     * điều khiển các button chức năng tạo mới
     */
    private void buttonCreater() {
        btnAdd.setVisible(true);
        btnCanEdit.setVisible(false);
        btnEdit.setVisible(false);
        btnRemove.setVisible(false);
        btnRefresh.setVisible(false);
    }

    /**
     * điều khiển các button chức năng xem,chỉnh sửa
     */
    private void buttonShow() {
        btnRefresh.setVisible(true);
        btnAdd.setVisible(false);
        btnCanEdit.setVisible(true);
        btnEdit.setVisible(true);
        btnEdit.setEnabled(false);
        btnRemove.setVisible(true);
        btnRemove.setEnabled(false);
    }

    @Override
    public void setTopComponent(EnterpriseManagerTopComponent topComponent) {
        this.topComponent = topComponent;
    }

    @Override
    public void loadDefault() {
        if (panelControlShowInformation != null) {
            panelControlShowInformation.loadDeault();
        }
    }
}
