/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DialogEnterpriseType.java
 *
 * Created on May 24, 2012, 3:17:53 PM
 */
package vn.com.hkt.em.enterprise.presentation.dialog.spi;

import java.awt.Color;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import org.openide.util.lookup.ServiceProvider;
import vn.com.hkt.em.enterprise.business.provider.dialog.spi.EnterpriseTypeDialogProvider;
import vn.com.hkt.em.enterprise.data.entities.EnterpriseType;
import vn.com.hkt.em.enterprise.presentation.dialog.api.IEnterpriseTypeDialog;
import vn.com.hkt.em.enterprise.presentation.dialog.spi.tablemodel.EnterpriseTypeTableModel;

/**
 *
 * @author duong
 */
@ServiceProvider(service = IEnterpriseTypeDialog.class)
public class DialogEnterpriseType extends javax.swing.JDialog implements IEnterpriseTypeDialog {

    private JComboBox comboBox;
    private EnterpriseTypeDialogProvider provider = new EnterpriseTypeDialogProvider();
    private final long LEVEL = 1;

    /** Creates new form DialogEnterpriseType */
    public DialogEnterpriseType(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public DialogEnterpriseType() {
        initComponents();
        this.setModal(true);
        this.setLocationRelativeTo(null);
        resetData();
        loadTable();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbEnterpriseTypeName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtEnterpriseTypeName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        btnReset = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableEnterpriseTypeDialog = new javax.swing.JTable();
        lbMessenger = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        lbEnterpriseTypeName.setText(org.openide.util.NbBundle.getMessage(DialogEnterpriseType.class, "DialogEnterpriseType.lbEnterpriseTypeName.text")); // NOI18N

        jLabel2.setText(org.openide.util.NbBundle.getMessage(DialogEnterpriseType.class, "DialogEnterpriseType.jLabel2.text")); // NOI18N

        txtEnterpriseTypeName.setText(org.openide.util.NbBundle.getMessage(DialogEnterpriseType.class, "DialogEnterpriseType.txtEnterpriseTypeName.text")); // NOI18N
        txtEnterpriseTypeName.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtEnterpriseTypeNameCaretUpdate(evt);
            }
        });

        jScrollPane1.setViewportView(txtDescription);

        btnReset.setText(org.openide.util.NbBundle.getMessage(DialogEnterpriseType.class, "DialogEnterpriseType.btnReset.text")); // NOI18N
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnAdd.setText(org.openide.util.NbBundle.getMessage(DialogEnterpriseType.class, "DialogEnterpriseType.btnAdd.text")); // NOI18N
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnEdit.setText(org.openide.util.NbBundle.getMessage(DialogEnterpriseType.class, "DialogEnterpriseType.btnEdit.text")); // NOI18N
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnRemove.setText(org.openide.util.NbBundle.getMessage(DialogEnterpriseType.class, "DialogEnterpriseType.btnRemove.text")); // NOI18N
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        tableEnterpriseTypeDialog.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableEnterpriseTypeDialog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableEnterpriseTypeDialogMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableEnterpriseTypeDialog);

        lbMessenger.setForeground(java.awt.Color.red);
        lbMessenger.setText(org.openide.util.NbBundle.getMessage(DialogEnterpriseType.class, "DialogEnterpriseType.lbMessenger.text")); // NOI18N

        btnRefresh.setText(org.openide.util.NbBundle.getMessage(DialogEnterpriseType.class, "DialogEnterpriseType.btnRefresh.text")); // NOI18N
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbEnterpriseTypeName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtEnterpriseTypeName, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnReset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnAdd)
                                .addGap(6, 6, 6)
                                .addComponent(btnRefresh)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEdit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRemove)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
                    .addComponent(lbMessenger, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEnterpriseTypeName)
                    .addComponent(txtEnterpriseTypeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReset)
                    .addComponent(btnAdd)
                    .addComponent(btnEdit)
                    .addComponent(btnRemove)
                    .addComponent(btnRefresh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbMessenger)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void txtEnterpriseTypeNameCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtEnterpriseTypeNameCaretUpdate
    if (txtEnterpriseTypeName.getText().isEmpty()) {
        lbEnterpriseTypeName.setForeground(Color.red);
    }
    lbEnterpriseTypeName.setForeground(Color.black);
}//GEN-LAST:event_txtEnterpriseTypeNameCaretUpdate

private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
    resetData();
}//GEN-LAST:event_btnResetActionPerformed

private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
    addData(0);// TODO add your handling code here:
}//GEN-LAST:event_btnAddActionPerformed

private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
    provider.refreshData();
    refreshData();
}//GEN-LAST:event_btnRefreshActionPerformed

private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
    editData();
}//GEN-LAST:event_btnEditActionPerformed

private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
    removeData();
}//GEN-LAST:event_btnRemoveActionPerformed

private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
    comboBox.setModel(new DefaultComboBoxModel(provider.getListEnterpriseType().toArray()));
}//GEN-LAST:event_formWindowClosed

private void tableEnterpriseTypeDialogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableEnterpriseTypeDialogMouseClicked
    provider.setDataView(provider.getListEnterpriseType().get(tableEnterpriseTypeDialog.getSelectedRow()));
    refreshData();
}//GEN-LAST:event_tableEnterpriseTypeDialogMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogEnterpriseType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogEnterpriseType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogEnterpriseType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogEnterpriseType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                DialogEnterpriseType dialog = new DialogEnterpriseType(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbEnterpriseTypeName;
    private javax.swing.JLabel lbMessenger;
    private javax.swing.JTable tableEnterpriseTypeDialog;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextField txtEnterpriseTypeName;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setComboBox(JComboBox comboBox) {
        this.comboBox = comboBox;
    }

    @Override
    public String getDescriptionPanel() {
        return "Giao diện chỉnh sửa loại hình doanh nghiệp";
    }

    @Override
    public void resetData() {
        txtDescription.setText("");
        txtEnterpriseTypeName.setText("");
        btnAdd.setEnabled(true);
        btnEdit.setEnabled(false);
        btnRemove.setEnabled(false);
        btnRefresh.setEnabled(false);
        provider.setDataView(new EnterpriseType());
        lbMessenger.setVisible(false);
    }

    private boolean getData() {
        if (!checkData()) {
            return false;
        }
        provider.getDataViewCurrent().setDescription(txtDescription.getText());
        provider.getDataViewCurrent().setEnterpriseTypeName(txtEnterpriseTypeName.getText());
        return true;
    }

    @Override
    public long addData(long idParent) {
        if (!getData()) {
            return ID_FAILD;
        } else {
            if (provider.addData(idParent) < 0) {
                lbMessenger.setVisible(true);
                lbMessenger.setText("Hãy xem lại phần hiển thị màu đỏ");
                return ID_FAILD;
            } else {
                lbMessenger.setVisible(false);
                resetData();
                loadTable();
                return provider.getDataViewCurrent().getId();
            }
        }

    }

    @Override
    public void refreshData() { // hien thi tu table len txt
        txtDescription.setText(provider.getDataViewCurrent().getDescription());
        txtEnterpriseTypeName.setText(provider.getDataViewCurrent().getEnterpriseTypeName());
        canEditData();
    }

    @Override
    public void canEditData() {
        btnAdd.setEnabled(false);
        btnEdit.setEnabled(true);
        btnRefresh.setEnabled(true);
        btnRemove.setEnabled(true);
    }

    @Override
    public long editData() {
        getData();
        if (provider.editData() < 0) {
            lbMessenger.setVisible(true);
            lbMessenger.setText("Hãy xem lại phần hiển thị màu đỏ");
            return ID_FAILD;
        } else {
            lbMessenger.setVisible(false);
            resetData();
            loadTable();
            return provider.getDataViewCurrent().getId();
        }
    }

    @Override
    public long removeData() {
        long id = provider.getDataViewCurrent().getId();
        if (provider.removeData() < 0) {
            lbMessenger.setVisible(true);
            lbMessenger.setText("Hãy chắc chắn rằng bạn đã chọn đối tượng để xóa");
            return ID_FAILD;
        } else {
            lbMessenger.setVisible(false);
            resetData();
            loadTable();
            return id;
        }
    }

    @Override
    public int getFunction() {
        return ID_FAILD;
    }

    @Override
    public boolean checkData() {
        return true;
    }

    @Override
    public void loadDefault() {
    }

    private void loadTable() {
        provider.loadAllEnterpriseType();
        tableEnterpriseTypeDialog.setModel(new EnterpriseTypeTableModel(provider.getListEnterpriseType()));
    }
}
